"""Initial migration.

Revision ID: f264f02c956e
Revises: 
Create Date: 2025-03-12 20:59:06.906355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f264f02c956e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('college', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('admission_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('is_hosteller', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint('uq_user_admission_number', ['admission_number'])  # FIXED

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_admission_number', type_='unique')  # FIXED
        batch_op.drop_column('is_hosteller')
        batch_op.drop_column('admission_number')
        batch_op.drop_column('college')

    # ### end Alembic commands ###
